[project]
name = "smmbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.21.0",
    "asyncpg>=0.30.0",
    "black>=25.1.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "ruff>=0.12.8",
    "vk-api>=11.10.0",
]
